### PR TITLE
Allow any chars after drawing commands

### PR DESCRIPTION
**Pull request by Dador**
Hi!

Few fixes for stability.

### 1 commit:
Parse error happens on any of these lines:
```
Dialogue: 3,0:00:28.96,0:00:31.71,koisuru romaji,,0,0,0,fx,{\fad(0,120)\an5\pos(546.15363580885, 38.454659853818)\1a&HFF&\blur0.7\fr-2\fscx300\fscy300\bord0\t(-12.6328125,47.3671875,\1a&H00&\fscx99\fscy99)\1c&H8B71EB&\p1\t(200,248,0.4,\fscx128.7\fscy128.7)\t(272,440,2,\fscx99\fscy99)}m 25 17 b 31 9 46 10 47 24 b 45 35 37 38 31 40 b 27 42 24 43 19 47 b 16 42 13 38 9 34 b 0 27 0 15 4 11 b 15 0 26 13 25 17k
Dialogue: 3,0:00:28.96,0:00:31.71,koisuru romaji,,0,0,0,fx,{\fad(0,120)\an5\pos(563.26161809146, 43.660800665746)\1a&HFF&\blur0.7\fr-35\fscx300\fscy300\bord0\t(4.1953125,64.1953125,\1a&H00&\fscx82\fscy82)\1c&H8B71EB&\p1\t(200,248,0.4,\fscx106.6\fscy106.6)\t(272,440,2,\fscx82\fscy82)}m 25 17 b 31 9 46 10 47 24 b 45 35 37 38 31 40 b 27 42 24 43 19 47 b 16 42 13 38 9 34 b 0 27 0 15 4 11 b 15 0 26 13 25 17 m
```

Fix works the same as libass (just skip "odd extra value"): https://github.com/libass/libass/blob/master/libass/ass_drawing.c#L184

### 2 commit:
Subtitles not visible if threre is no "[Script Info]" on first line (cause PlayResX/Y not parsed).
```
Title: Default Aegisub file
ScriptType: v4.00+
```

Both examples from real subtitles.

### CODE REVIEW

**Comment by Arnavion** [comment]
Since you undid a lot of the first commit in the third commit, can you rebase and combine them into one commit?

Can you add a test to each commit? For the first commit, copy an existing test .ass file and remove the `[ScriptInfo]` header, and in miscellaenous.js copy a parser test and check that resolutionX is the correct value.

For the second commit, add a parser test for each of these next to the other drawing part tests:
    - `m 100 200 l 300 400k` -> `[MoveInstruction(100, 200), LineInstruction(300, 400)]`
    - `m 100 k 200` -> `[]`
    - `k 100 m 200 300` -> '[MoveInstruction(200, 300)]'
    - `m 100 200 k 300 400 l 500 600` -> `[MoveInstruction(100, 200), MoveInstruction(300, 400), LineInstruction(500, 600)]`

By the way, that second example shows that your change does not hav exactly the same behavior as libass. libass will also ignore unrecognized text *between* the valid parts of the drawing instruction (i.e. `m 100 k 200` will be parsed as if it was `m 100 200`) whereas with your change the whole thing will be treated as text. To fix that you'll have to change the three parse_drawingInstruction* functions as well to ignore non-numbers.

**Comment by Arnavion** [comment]
Sorry, maybe I wasn't clear. Your test

```javascript
tdd.test("Unrecognized text between valid parts of the instruction", parserTest("m 100 k 200", "drawingInstructions", []));
```

should really be

```javascript
tdd.test("Unrecognized text between valid parts of the instruction", parserTest("m 100 k 200", "drawingInstructions", [
    new libjass.parts.drawing.MoveInstruction(100, 200)
]));
```

to match libass's behavior.

**Comment by Dador** [comment]
> By the way, that second example shows that your change does not have exactly the same behavior as libass. libass will also ignore unrecognized text between the valid parts of the drawing instruction (i.e. m 100 k 200 will be parsed as if it was m 100 200) whereas with your change the whole thing will be treated as text. To fix that you'll have to change the three parse_drawingInstruction* functions as well to ignore non-numbers.

Yeah, I missed that part. But just ignoring non-numbers lead us to wrong behavior too. With such fix result of parsing "l m 100 200" would be LineInstruction(100, 200) but it should be MoveInstruction(100, 200).

I tested that behavior in both libass and VSFilter. Test dialogue:
```Dialogue: 0,0:00:00.00,0:00:08.00,Base01,,0,0,0,,{\p1}l m 300 -200 l 200 0 l 400 10```
Result is the same - move instruction.

I think we can ignore only chars that not used in drawing commands (so ignore all chars except numbers and "m, n, l, b, s, p, c"). But maybe that's not the best way to fix that. What do you think?

**Comment by Arnavion** [comment]
Oh yes, I didn't think of that. Your suggestion is one way. Another way is to merge the three parse_drawingInstruction* into parse_drawingInstructions so then the lastType can handle it. Let me think which one I prefer.

**Comment by Arnavion** [comment]
I've merged the script info section change as https://github.com/Arnavion/libjass/commit/1df6c44 - it had one bug that it wasn't setting the current section name, which broke the minimalASS, so I fixed that.

**Comment by Arnavion** [comment]
I decided merging the three parse instruction functions into the main one is better - the parse is context-sensitive so pretending otherwise is pointless.

I've pushed that to https://github.com/Arnavion/libjass/compare/drawing and added a few tests. Does it look okay to you?

**Comment by Dador** [comment]
Yeah, looks good!

**Comment by Arnavion** [comment]
Thanks. Merged as https://github.com/Arnavion/libjass/commit/f21b90b

**Pull request closed without merging**
